version: '3'

services:
  message-db:
    container_name: message-db
    image: inventicon/message-db:14-bullseye
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - ./data:/var/lib/postgresql/data
